## 2.2

In [53]:
import math
import pandas as pd
import numpy as np
from numpy.random import seed
from numpy.random import normal

In [54]:
# generate 200 samples
X = normal(loc=0, scale=1, size=200)
Y = normal(loc=0, scale=1, size=200)
print(X[0:5])
print(Y[0:5])

[ 0.2773202   0.75737185 -0.57414883  0.75476022  0.31517587]
[-2.20933962  0.52711645  0.03703593 -0.83097569  0.43222653]


In [55]:
# Z = ρX+sqrt{(1 − ρ^2)}Y
ρ = 0.5
Z = ρ * X + math.sqrt(1 - ρ ** 2) * Y
print(Z[0:5])

[-1.77468414  0.83518217 -0.25500036 -0.34226595  0.53190709]


In [56]:
Corr = np.corrcoef(X,Z)
print(f'Corr={Corr[1,0]}')

Corr=0.4760221982732191


In [57]:
corr_2f=round(Corr[1,0],1)
print(corr_2f)

0.5


At the level of one decimal place and 200 samples, the correlation coefficient a is equal to the coefficient ρ.